spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:canal_de_etica_registros}
    username: ${DB_USER:canal_de_etica}
    password: ${DB_PASSWORD:canal_de_etica}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
