alter table roles
    add column if not exists type varchar(30) not null default 'FUNCTIONAL';

update roles
set type = 'SYSTEM'
where upper(name) = 'ADMIN';

create table if not exists organization_unit_types (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(120) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists organization_units (
    id bigint generated by default as identity primary key,
    type_id bigint not null,
    code varchar(80) not null,
    name varchar(160) not null,
    parent_id bigint,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint fk_organization_units_type foreign key (type_id) references organization_unit_types (id),
    constraint fk_organization_units_parent foreign key (parent_id) references organization_units (id),
    constraint uk_organization_units_type_code unique (type_id, code)
);

create table if not exists role_organization_scopes (
    id bigint generated by default as identity primary key,
    role_id bigint not null,
    organization_unit_id bigint not null,
    scope_level varchar(20) not null,
    constraint fk_role_organization_scopes_role foreign key (role_id) references roles (id),
    constraint fk_role_organization_scopes_unit foreign key (organization_unit_id) references organization_units (id),
    constraint uk_role_organization_scope_unit unique (role_id, organization_unit_id)
);

insert into permissions (name, description)
select 'ORGANIZATION_UNITS_VIEW', 'Visualizar estrutura organizacional.'
where not exists (select 1 from permissions where name = 'ORGANIZATION_UNITS_VIEW');

insert into permissions (name, description)
select 'ORGANIZATION_UNITS_CREATE', 'Criar estrutura organizacional.'
where not exists (select 1 from permissions where name = 'ORGANIZATION_UNITS_CREATE');

insert into permissions (name, description)
select 'ORGANIZATION_UNITS_EDIT', 'Editar estrutura organizacional.'
where not exists (select 1 from permissions where name = 'ORGANIZATION_UNITS_EDIT');

insert into permissions (name, description)
select 'ORGANIZATION_UNITS_DELETE', 'Excluir estrutura organizacional.'
where not exists (select 1 from permissions where name = 'ORGANIZATION_UNITS_DELETE');

insert into permissions (name, description)
select 'ROLES_MANAGE_ORGANIZATION_SCOPES', 'Gerenciar escopos organizacionais de perfis.'
where not exists (select 1 from permissions where name = 'ROLES_MANAGE_ORGANIZATION_SCOPES');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.name in (
    'ORGANIZATION_UNITS_VIEW',
    'ORGANIZATION_UNITS_CREATE',
    'ORGANIZATION_UNITS_EDIT',
    'ORGANIZATION_UNITS_DELETE',
    'ROLES_MANAGE_ORGANIZATION_SCOPES'
)
where upper(r.name) = 'ADMIN'
  and not exists (
      select 1
      from role_permissions rp
      where rp.role_id = r.id
        and rp.permission_id = p.id
  );
