create table tipo_fato (
    id bigint generated by default as identity primary key,
    nome varchar(180) not null unique,
    ativo boolean not null default true,
    ordem integer not null
);

create table registro (
    id uuid primary key,
    protocolo varchar(80) not null unique,
    nome varchar(160),
    email varchar(160),
    telefone varchar(40),
    relato text not null,
    tipo_fato_id bigint not null,
    tipo_fato_nome varchar(180) not null,
    status varchar(40) not null default 'RECEBIDO',
    origem varchar(40) not null default 'API_PUBLICA',
    criado_em timestamp not null default current_timestamp,
    atualizado_em timestamp not null default current_timestamp,
    constraint fk_registro_tipo_fato foreign key (tipo_fato_id) references tipo_fato (id)
);

create table registro_anexo (
    id uuid primary key,
    registro_id uuid not null,
    nome_original varchar(255) not null,
    nome_fisico varchar(255) not null,
    content_type varchar(120) not null,
    tamanho bigint not null,
    hash varchar(128) not null,
    caminho varchar(500) not null,
    criado_em timestamp not null default current_timestamp,
    constraint fk_registro_anexo_registro foreign key (registro_id) references registro (id)
);

create table api_client (
    id uuid primary key,
    nome varchar(120) not null,
    api_key_hash varchar(255) not null,
    ativo boolean not null default true,
    criado_em timestamp not null default current_timestamp,
    ultimo_uso_em timestamp
);

create index idx_registro_tipo_fato_id on registro (tipo_fato_id);
create index idx_registro_status on registro (status);
create index idx_registro_criado_em on registro (criado_em);
create index idx_registro_anexo_registro_id on registro_anexo (registro_id);

insert into tipo_fato (nome, ativo, ordem) values
    ('Conduta', true, 1),
    ('Assédio sexual', true, 2),
    ('Violência física', true, 3),
    ('Corrupção (tanto interna quanto envolvendo governo)', true, 4),
    ('Prática de crimes hediondos (inclusive fora da empresa)', true, 5),
    ('Desvios de dinheiro e/ou material', true, 6),
    ('Violação de leis ambientais', true, 7),
    ('Destruição ou danificação de patrimônio da empresa', true, 8),
    ('Porte de arma não autorizado nas dependências da empresa', true, 9),
    ('Uso de substâncias ilícitas', true, 10),
    ('Retaliação a denunciantes de boa-fé', true, 11),
    ('Agiotagem', true, 12),
    ('Decisões em desacordo com a lei', true, 13),
    ('Disseminação de informações caluniosas difamatórias sobre a empresa, seus colaboradores ou clientes', true, 14),
    ('Assédio moral', true, 15),
    ('Desrespeito a normas de segurança', true, 16),
    ('Discriminação e preconceito', true, 17),
    ('Uso indevido de dados e informações', true, 18),
    ('Adulteração de cadastro de clientes ou fornecedores', true, 19),
    ('Disseminação de informações falsas sobre a empresa', true, 20),
    ('Desrespeito aos colegas (salvo quando caracterizar assédio)', true, 21),
    ('Abuso do Canal de Denúncia', true, 22),
    ('Descumprimento ou não observância de processos e procedimentos', true, 23),
    ('Decisões em desacordo com normas internas', true, 24),
    ('Outros', true, 25);
