create table roles (
    id bigint generated by default as identity primary key,
    name varchar(60) not null unique,
    description varchar(160)
);

create table permissions (
    id bigint generated by default as identity primary key,
    name varchar(80) not null unique,
    description varchar(160)
);

create table usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    email varchar(160) not null unique,
    senha varchar(255) not null,
    ativo boolean not null default true,
    avatar_url varchar(300),
    criado_em timestamp with time zone not null default current_timestamp
);

create table role_permissions (
    role_id bigint not null,
    permission_id bigint not null,
    primary key (role_id, permission_id),
    constraint fk_role_permissions_role foreign key (role_id) references roles (id),
    constraint fk_role_permissions_permission foreign key (permission_id) references permissions (id)
);

create table usuario_roles (
    usuario_id bigint not null,
    role_id bigint not null,
    primary key (usuario_id, role_id),
    constraint fk_usuario_roles_usuario foreign key (usuario_id) references usuarios (id),
    constraint fk_usuario_roles_role foreign key (role_id) references roles (id)
);

create table user_preferences (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null unique,
    tema varchar(40) not null,
    idioma varchar(20) not null,
    notificacoes boolean not null default true,
    cor_primaria varchar(20) not null,
    cor_secundaria varchar(20) not null,
    preferencia_visual varchar(20) not null,
    menu_principal varchar(20) not null,
    constraint fk_user_preferences_usuario foreign key (usuario_id) references usuarios (id)
);

create table user_sessions (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null,
    criada_em timestamp with time zone not null default current_timestamp,
    constraint fk_user_sessions_usuario foreign key (usuario_id) references usuarios (id)
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null,
    token varchar(120) not null unique,
    session_id bigint not null unique,
    expires_at timestamp with time zone not null,
    constraint fk_refresh_tokens_usuario foreign key (usuario_id) references usuarios (id),
    constraint fk_refresh_tokens_session foreign key (session_id) references user_sessions (id)
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    usuario varchar(160) not null,
    acao varchar(80) not null,
    entidade varchar(80) not null,
    entidade_id bigint,
    timestamp_registro timestamp with time zone not null default current_timestamp
);

create table branding_settings (
    id bigint generated by default as identity primary key,
    nome_plataforma varchar(120) not null,
    subtitulo_institucional varchar(255) not null,
    tema varchar(20) not null,
    cor_primaria varchar(20) not null,
    cor_secundaria varchar(20) not null,
    densidade_visual varchar(20) not null,
    login_background_mode varchar(32) not null,
    logo_url varchar(255),
    login_background_url varchar(255)
);
